source: app
destination: public
permalink: pretty
exclude:
- .gitignore
- .rvmrc
- assets/images/source/
- assets/stylesheets/source/
- config.rb
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- public
